const SUBJECTS = [
   "English",
   "History",
   "Science",
   "Math",
   "Physics",
   "Chemistry",
   "Biology",
   "College Prep - SATs/ACTs",
   "College Prep - Essays",
   "Writing",
   "Economics",
   "Studio/Visual Art",
   "Music",
   "Theatre",
   "Design",
   "Computer Science - Python",
   "Computer Science - C/C++",
   "Computer Science - Java",
   "AP Physics C",
   "AP Calculus AB",
   "AP Calculus BC",
   "AP Statistics",
   "AP English Literature",
   "AP English Language",
   "AP World History",
   "AP US History",
   "AP Chemistry",
   "AP Biology",
   "AP European History",
   "Spanish",
   "French",
   "Chinese",
   "German",
   "Latin",
   "Japanese",
  ];
  
const TAGS = ["Early Childhood Learning", "Preschool", "Elementary School", "Middle School","High School"];

module.exports = {TAGS, SUBJECTS};